# Numpy

In [1]:
!conda list numpy


# packages in environment at C:\Users\Govind Thakur\Anaconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.15.4           py37h19fb1c0_0  
numpy-base                1.15.4           py37hc3f5095_0  
numpydoc                  0.8.0                    py37_0  


In [6]:
import numpy as np
x = np.array([1,2,3,4,5,6])
print(x)
print(type(x))
print(x.dtype)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
int32


In [7]:
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
print (y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
y.shape

(3, 3)

In [10]:
y.dtype

dtype('int32')

In [11]:
y.size

9

In [15]:
# We create a rank 1 ndarray from a Python list that contains integers and strings
x = np.array([1, 2, 'World'])

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  ['1' '2' 'World']

x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U11


In [17]:
import numpy as np
x=np.zeros((4,3)).reshape((3,4))
print (x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
z=np.ones((2,5))
print (z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
z.dtype

dtype('float64')

In [20]:
x.dtype

dtype('float64')

In [21]:
y=np.random.random((2,3))
print (y)

[[0.52907799 0.36382714 0.09658139]
 [0.39150931 0.97404642 0.74028185]]


In [22]:
a=int(input("Enter the rank of the matrix:"))
b=np.eye((a))
print(b)

Enter the rank of the matrix:4
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
b.dtype

dtype('float64')

In [24]:
d=np.arange(2,40)
print(d)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [25]:
p=np.linspace(0,25,10)
print(p)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [26]:
z= np.arange(1,21)
print (z)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [27]:
z=np.delete(z,-1)
print(z)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [28]:
z=np.append(z,20)
print(z)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [29]:
z=np.reshape(z,(4,5))
print (z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [30]:
z=np.delete(z,1,axis=0)
print(z)

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [31]:
z=np.delete(z,1,axis=1)
print(z)

[[ 1  3  4  5]
 [11 13 14 15]
 [16 18 19 20]]


In [32]:
z=np.insert(z,1,[2,12,17],axis=1)
print(z)

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [33]:
z=np.insert(z,1,[6,7,8,9,10],axis=0)
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [34]:
# We create two rank 2 ndarrays
import numpy as np
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)

# We print X
print()
print('X = \n', X)

# We print Y
print()
print('Y = \n', Y)
print()

# We perform basic element-wise operations using arithmetic symbols and functions
print('X + Y = \n', X + Y)
print()
print('add(X,Y) = \n', np.add(X,Y))
print()
print('X - Y = \n', X - Y)
print()
print('subtract(X,Y) = \n', np.subtract(X,Y))
print()
print('X * Y = \n', X * Y)
print()
print('multiply(X,Y) = \n', np.multiply(X,Y))
print()
print('X / Y = \n', X / Y)
print()
print('divide(X,Y) = \n', np.divide(X,Y))


X = 
 [[1 2]
 [3 4]]

Y = 
 [[5.5 6.5]
 [7.5 8.5]]

X + Y = 
 [[ 6.5  8.5]
 [10.5 12.5]]

add(X,Y) = 
 [[ 6.5  8.5]
 [10.5 12.5]]

X - Y = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

subtract(X,Y) = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

X * Y = 
 [[ 5.5 13. ]
 [22.5 34. ]]

multiply(X,Y) = 
 [[ 5.5 13. ]
 [22.5 34. ]]

X / Y = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]

divide(X,Y) = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]


In [35]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4])

# We print x
print()
print('x = ', x)

# We apply different mathematical functions to all elements of x
print()
print('EXP(x) =', np.exp(x))
print()
print('SQRT(x) =',np.sqrt(x))
print()
print('POW(x,2) =',np.power(x,2)) # We raise all elements to the power of 2


x =  [1 2 3 4]

EXP(x) = [ 2.71828183  7.3890561  20.08553692 54.59815003]

SQRT(x) = [1.         1.41421356 1.73205081 2.        ]

POW(x,2) = [ 1  4  9 16]


In [36]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))


X = 
 [[1 2]
 [3 4]]

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]


In [37]:
Z=np.arange(1,17)
print(Z)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [38]:
Z=np.reshape(Z,[4,4])

In [39]:
print(Z)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [40]:
Z=np.reshape(Z,[4,4])
print(Z)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [41]:
Y=np.ones([4,4])
print(Y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [42]:
Z=[1,1,1,1]
Y=np.add(Y,Z)
print(Y)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [44]:
X = np.ones((4,4)) * np.arange(1,5)
print(X)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [22]:
!conda list pandas

# packages in environment at C:\Users\Govind Thakur\Anaconda3:
#
# Name                    Version                   Build  Channel
pandas                    0.23.4           py37h830ac7b_0  


# Pandas

In [46]:
import pandas as pd

In [47]:
groceries= pd.Series(data=[30,6,'Yes','No'], index=['eggs','apples','milk','bread'])
groceries

eggs       30
apples      6
milk      Yes
bread      No
dtype: object

In [48]:
'bread'in groceries

True

In [49]:
groceries

eggs       30
apples      6
milk      Yes
bread      No
dtype: object

In [50]:
groceries['eggs']

30

In [51]:
groceries[['milk','bread']]


milk     Yes
bread     No
dtype: object

In [52]:
groceries[0]

30

In [53]:
groceries[-1]

'No'

In [54]:
groceries[[0,3]]

eggs     30
bread    No
dtype: object

In [55]:
groceries['eggs']=21
groceries

eggs       21
apples      6
milk      Yes
bread      No
dtype: object

In [56]:
groceries

eggs       21
apples      6
milk      Yes
bread      No
dtype: object

In [57]:
# We create a Pandas Series that stores a grocery list of just fruits
fruits= pd.Series(data = [10, 6, 3,], index = ['apples', 'oranges', 'bananas'])

# We display the fruits Pandas Series
fruits

apples     10
oranges     6
bananas     3
dtype: int64

In [58]:
# We print fruits for reference
print('Original grocery list of fruits:\n ', fruits)

# We perform basic element-wise operations using arithmetic symbols
print()
print('fruits + 2:\n', fruits + 2) # We add 2 to each item in fruits
print()
print('fruits - 2:\n', fruits - 2) # We subtract 2 to each item in fruits
print()
print('fruits * 2:\n', fruits * 2) # We multiply each item in fruits by 2 
print()
print('fruits / 2:\n', fruits / 2) # We divide each item in fruits by 2
print()

Original grocery list of fruits:
  apples     10
oranges     6
bananas     3
dtype: int64

fruits + 2:
 apples     12
oranges     8
bananas     5
dtype: int64

fruits - 2:
 apples     8
oranges    4
bananas    1
dtype: int64

fruits * 2:
 apples     20
oranges    12
bananas     6
dtype: int64

fruits / 2:
 apples     5.0
oranges    3.0
bananas    1.5
dtype: float64



In [59]:
fruits

apples     10
oranges     6
bananas     3
dtype: int64

In [60]:
# We import NumPy as np to be able to use the mathematical functions
import numpy as np

# We print fruits for reference
print('Original grocery list of fruits:\n', fruits)

# We apply different mathematical functions to all elements of fruits
print()
print('EXP(X) = \n', np.exp(fruits))
print() 
print('SQRT(X) =\n', np.sqrt(fruits))
print()
print('POW(X,2) =\n',np.power(fruits,2)) # We raise all elements of fruits to the power of 2

Original grocery list of fruits:
 apples     10
oranges     6
bananas     3
dtype: int64

EXP(X) = 
 apples     22026.465795
oranges      403.428793
bananas       20.085537
dtype: float64

SQRT(X) =
 apples     3.162278
oranges    2.449490
bananas    1.732051
dtype: float64

POW(X,2) =
 apples     100
oranges     36
bananas      9
dtype: int64


### Pandas DataFrames

In [65]:
import pandas as pd
items={'Bob':pd.Series([245,25,51], index=['bike','pants','watch']),'Alice':pd.Series([40,110,500,45],index=['book','glasses','bike','pants'])}
type(items)

dict

In [66]:
shopping_carts=pd.DataFrame(items)
shopping_carts

Bob  Alice
bike     245.0  500.0
book       NaN   40.0
glasses    NaN  110.0
pants     25.0   45.0
watch     51.0    NaN

In [67]:
item={'Bob':pd.Series([245,25,51]),'Alice':pd.Series([40,110,500,45])}
df=pd.DataFrame(item)

In [68]:
df

Bob  Alice
0  245.0     40
1   25.0    110
2   51.0    500
3    NaN     45

In [69]:
shopping_carts.index


Index(['bike', 'book', 'glasses', 'pants', 'watch'], dtype='object')

In [70]:
shopping_carts.columns

Index(['Bob', 'Alice'], dtype='object')

In [71]:
shopping_carts.values

array([[245., 500.],
       [ nan,  40.],
       [ nan, 110.],
       [ 25.,  45.],
       [ 51.,  nan]])

In [72]:
shopping_carts.values

array([[245., 500.],
       [ nan,  40.],
       [ nan, 110.],
       [ 25.,  45.],
       [ 51.,  nan]])

In [73]:
shopping_carts.size

10

In [74]:
shopping_carts.ndim

2

In [75]:
shopping_carts.shape

(5, 2)

In [76]:
shopping_carts.Alice['book']=19000


In [77]:
shopping_carts.Alice

bike         500.0
book       19000.0
glasses      110.0
pants         45.0
watch          NaN
Name: Alice, dtype: float64

In [79]:
import pandas as pd
import numpy as np
pd.set_option('precision',1)
books = pd.Series(data = ['Great Expectations', 'Of Mice and Men', 'Romeo and Juliet', 'The Time Machine', 'Alice in Wonderland' ])
authors = pd.Series(data = ['Charles Dickens', 'John Steinbeck', 'William Shakespeare', ' H. G. Wells', 'Lewis Carroll' ])

user_1 = pd.Series(data = [3.2, np.nan ,2.5])
user_2 = pd.Series(data = [5., 1.3, 4.0, 3.8])
user_3 = pd.Series(data = [2.0, 2.3, np.nan, 4])
user_4 = pd.Series(data = [4, 3.5, 4, 5, 4.2])
dat = {'Author':authors, 
       'Book Title':books, 
       'User 1':user_1,
       'User 2':user_2,
       'User 3':user_3,
       'User 4':user_4}
book_ratings = pd.DataFrame(dat)
book_ratings
book_ratings.fillna(book_ratings.mean(axis=0),inplace=True)
book_ratings

Author           Book Title  User 1  User 2  User 3  User 4
0      Charles Dickens   Great Expectations     3.2     5.0     2.0     4.0
1       John Steinbeck      Of Mice and Men     2.9     1.3     2.3     3.5
2  William Shakespeare     Romeo and Juliet     2.5     4.0     2.8     4.0
3          H. G. Wells     The Time Machine     2.9     3.8     4.0     5.0
4        Lewis Carroll  Alice in Wonderland     2.9     3.5     2.8     4.2

In [80]:
best_rated=book_ratings[(book_ratings==5).any(axis=1)]['Book Title'].values
best_rated

array(['Great Expectations', 'The Time Machine'], dtype=object)

In [ ]:
import pandas as pd

filename = 'chicago.csv'

# load data file into a dataframe
df = pd.read_csv(filename)

# convert the Start Time column to datetime
df['Start Time'] = pd.to_datetime(df['Start Time'])

# extract hour from the Start Time column to create an hour column
df['hour'] = df['Start Time'].dt.hour

# find the most popular hour
popular_hour = df['hour'].mode()[0]

print('Most Popular Start Hour:', popular_hour)

In [ ]:
import pandas as pd
pd.read_csv('chicago.csv')

In [ ]:
import pandas as pd
import numpy as np
a=np.arange(1,21)
for i in a:
    print (i,sep=' ')
    